

E_CLASSROOM_NAME = 'studentmain'
E_CLASSROOM_PROGRAM_NAME = E_CLASSROOM_NAME + '.exe'

STUDENTMAIN_NAME = 'studentmain'
IS_E_CLASSROOM_STUDENTMAIN = STUDENTMAIN_NAME.lower() == E_CLASSROOM_NAME.lower()